### PR TITLE
Chore: Refactor directory `third_party` to `assets`

### PR DESCRIPTION
**Pull request by gagan0123**
## Description

Moved `third_party` directory to `assets` directory as needed for verified build process.

### CODE REVIEW

**Comment by mohdsayed** [comment]
Related issue https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/28

**Review by amedina — APPROVED** [review]
LGTM. Ship it!

**Comment by gagan0123** [comment]
@mohdsayed 

There was a requirement for the verified build process, that was not allowing us to have `third_party` directory within the project because this project itself is treated as `third_party` and so it cannot have a `third_party`, therefore moved it to `assets`

**Comment by mohdsayed** [comment]
@amedina  I see but, Isn't that contradictory to what was mentioned in the issue as a must have?

> For any first-party Google open source projects, any code that Google does not own the copyright to or that Google has not received under Google's Contributor License Agreement **must be placed in a third_party** directory at the root of the project.

Should it be mentioned somewhere in the README? How would someone know what assets are third-party in general?

Related doc: https://opensource.google/documentation/reference/thirdparty

**Pull request merged**
