### PR TITLE
Update landing pages UI

### PR DESCRIPTION
**Pull request by mayan-000**
## Description
This PR adds code for updating the UI for the landing page with new content and styles.

## Testing Instructions
- Clone this branch and build the extension.
- Open PSAT panel and click on Site boundaries landing page.
- The page should open with 4 tiles showing new content.
- Click on any tile will open new page with docs related to the topic clicked.
- Try same Tracking protection and Private advertising landing pages.
- 

## Screenshot/Screencast
Screenshot 2024-05-03 at 12 40 26

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- ~This code is covered by unit tests to verify that it works as intended.~
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

Fixes #

### CODE REVIEW

**Review by mohdsayed — APPROVED** [review]

**Comment by gagan0123** [comment]
@mayan-000 @mohdsayed 

Can we please use the UTM parameters, `?utm_source=psat&utm_medium=extension` as added to other outbound links from the extension?

**Comment by gagan0123** [comment]
Ref: https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/506

**Comment by mohdsayed** [comment]
> @mayan-000 @mohdsayed
> 
> Can we please use the UTM parameters, `?utm_source=psat&utm_medium=extension` as added to other outbound links from the extension?

Done and pushed to `develop`

**Comment by gagan0123** [comment]
Thanks 👍

**Pull request merged**
