### PR TITLE
Refactor: Update order of PAT Section components

### LINKED ISSUE #824: Update order of PAT Section components
The order of the components in the Private Advertising section should be as follows:

1. Topics
2. Protected Audience
3. Attribution Reporting
4. Private Aggregation

### PR DESCRIPTION
**Pull request by amovar18**
## Description
This PR aims to reorder the items in the sidebar.

## Testing Instructions
- Clone the branch.
- In the terminal run `npm i` and then run `npm run build:ext`.
- You should see the order in PAT section as follows:
1. Topics
2. Protected Audience
3. Attribution Reporting
4. Private Aggregation

## Screenshot/Screencast

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- [x] This code is covered by unit tests to verify that it works as intended.
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

Fixes #824

### CODE REVIEW

**Comment by fellyph** [comment]
@amovar18 I think the items should be consistent between the sidebar and landing page:

Screenshot 2024-09-03 at 13 46 22

**Comment by fellyph** [comment]
I have checked the latest changes and all good now:

Screenshot 2024-09-03 at 13 54 31

**Comment by pavanpatil1** [comment]
Looks good @amovar18. 

I have a question: The page displays 'Attribution Reporting' correctly, but the navigation label only shows 'Attribution.' Shouldn't it also be labeled 'Attribution Reporting'?

Screenshot 2024-09-03 at 8 21 37 PM

**Review by mohdsayed — APPROVED** [review]
LGTM

**Pull request merged**
