### PR TITLE
Add Wiki section in the extension

### LINKED ISSUE #820: Add `Wiki` section
Integrate the project's Wiki within the Privacy Sandbox Analysis tool's feature areas, enabling users to view, search, and navigate through the project documentation without leaving the tool. 

The Wiki embed should provide the same user experience to users as when they access it directly in the Github repository.

Users can access the embedded Wiki from a  "Documentation" or "Help" section in the sidebar.

Reference: https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki

### PR DESCRIPTION
**Pull request by mohdsayed**
## Description
Dynamically fetch [ps-analysis-tool/wiki](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki) and use that in a new Wiki section in PSAT extension.

## Relevant Technical Choices

- Parse sidebar markup for text and create an object for using in React components.
- Implement resizable and sticky sidebar.
- Parse markup using `marked` npm package.
- Fetch Markdown files based on the selected page.
- Handle internal images to be fetched from GitHub.
- Open external links in a new tab.
-  Style markdown `github-markdown-css` and some custom CSS.
- Implementation of opening internal links within PSAT.
- Handle hash for scrolling the given section into view.

## Additional Information:

**Limitations:**
- Internal links open in a new tab.
- Menu item with ID is not included.

## Screenshot/Screencast

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- [x] This code is covered by unit tests to verify that it works as intended.
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

Fixes #820

### CODE REVIEW

**Comment by fellyph** [comment]
I have found a few suggestions for this Pull Request:

1. The container for the content should have a minimum size like the cookie Table
2. The Loading should follow the standard loading bar from the extension. Currently, the Wiki Loading is using a "Loading" message and the PSAT landing page is using a progress bar.

https://github.com/user-attachments/assets/01b8452b-3b4a-4493-8ee3-dc5f95a263d6

https://github.com/user-attachments/assets/fc286651-072b-4aa0-9937-97c376e2ee84

**Comment by milindmore22** [comment]
QA Issue
The text in the tables is not visible in dark mode 
image
image (1)

**Comment by milindmore22** [comment]
QA : In Dark mode the code snippets remains dark 

image

**Comment by pavanpatil1** [comment]
- [ ] If the wiki link is included in the extension, it should direct users to the internal wiki rather than to GitHub.

[internal linking.webm](https://github.com/user-attachments/assets/e786f394-76d0-4063-a876-b77dd50490aa)

---

- [ ] After selecting a sub-navigation menu item, the navigation does not appear as active.

[active.webm](https://github.com/user-attachments/assets/7c3314ba-b538-4646-b2c7-16e6afaa0419)

---


- [ ] The extra top padding is visible on all headings. It should not be visible, and the icons are not appearing.

Screenshot 2024-09-04 at 9 09 37 AM

**Comment by pavanpatil1** [comment]
Verified the fixes looks good. 

**Note:** As we discussed, the multi-tab debugging link on the settings page isn't directing to the specific wiki subpage because the content is integrated into the main page, and there isn't a separate subsection for it. This needs to be updated from wiki. 

[mutitab.webm](https://github.com/user-attachments/assets/48a7a466-ffce-4984-86ca-5454fbdce99c)

**Review by mayan-000 — APPROVED** [review]

**Pull request merged**
