### PR TITLE
Feature: Adds IBC compliance & Cookie Set attribute inside CookieDetails Card

### LINKED ISSUE #35: SameSite section in Cookies Menu Element of Privacy Analysis DevTools Panel
## Feature Request

**Description:**
SameSite section on Cookies Menu display area, capturing behaviors demonstrated in this [demo](https://samesite-sandbox.glitch.me/) and in these [examples](https://github.com/GoogleChromeLabs/samesite-examples). 

**Acceptance Criteria:**
- [ ] Convey complete information about SameSite
- [ ] Fit into Cookies Tab UI

**Additional Information:**
- [ ] [SameSite Cookies Explained](https://web.dev/samesite-cookies-explained/)
- [ ] [Incrementally better cookies](https://datatracker.ietf.org/doc/html/draft-west-cookie-incrementalism-00)
- [ ] [SameSite Recipes](https://web.dev/samesite-cookie-recipes/)

### PR DESCRIPTION
**Pull request by mayan-000**
## Description

This pull request introduces the IBC (Incrementally Better Cookies) compliance attribute inside the CookieDetails Card component that displays the SameSite attribute of cookies and verifies if their values align with the IBC draft proposal.

The implementation ensures that cookies adhere to the recommended SameSite attribute values, such as "Lax" by default and "None" with the "Secure" flag for cross-site delivery. It provides a clear overview of the compliance status, helping developers verify if their cookies meet the IBC standards.

## Relevant Technical Choices

- Introduces a key-value pair-based UI inside the CookieDetails Card.
  - Adds two new keys: "IBC Compliant" and "Cookie Set" to represent specific attributes.
  - Enables a long hover over each key to display a summary of their use cases, providing contextual information.
- Updates Cookie Headers Parsing Mechanism:
  - Enhances the cookie headers parsing mechanism to streamline the values of a cookie.
  - Takes into account the cookie's header parsed entries, Chrome cookie-store cookie, and previously parsed cookie.
  - Improves the accuracy and consistency of parsed cookie values, ensuring reliable data extraction.
  
## Testing Instructions

- Open a website (say https://indianexpress.com/), now open the Privacy analysis panel in devtools.
- Click on the tab Cookies, and click on any cookie.
- In the CookieDetails card, you can see IBC Compliant and Cookie Set will be visible with relevant values.

## Screenshot/Screencast

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/b5c3f693-ab00-45bf-a4b3-9802eb3dc28f

Screenshot 2023-07-11 at 5 19 56 PM

Screenshot 2023-07-11 at 5 35 01 PM

---

Fixes #35

### CODE REVIEW

**Review by sayedtaqui — CHANGES_REQUESTED** [review]

**Comment by sayedtaqui** [comment]
@mayan-000 there seem to a small lint warning
```log
/Users/sayedtaqui/projects/ps-analysis-tool/packages/extension/src/utils/getCookie.ts
  21:1  warning  The type 'chrome' is undefined  jsdoc/no-undefined-types
```

**Comment by sayedtaqui** [comment]
@mayan-000 The colors have changed, they weren't green.

image

image

**Comment by sayedtaqui** [comment]
@mayan-000 I tested this on https://samesite-sandbox.glitch.me/ and it seems to work as expected. Is there any website or demo example where one of the cookie compliance is "No" for testing.

**Comment by mayan-000** [comment]
> @mayan-000 I tested this on https://samesite-sandbox.glitch.me/ and it seems to work as expected. Is there any website or demo example where one of the cookie compliance is "No" for testing.
> 
> Also please add a little more detail for "Cookie Set" `abbr` as its not very clear why the cookie was not set.

@sayedtaqui 
There is a cookie on edition.cnn.com
1. Open the website and scroll a little.
2. Open the Extension panel and look out for `test_cookie`, it shows compliance and set-cookie both as "No".

**Comment by sayedtaqui** [comment]
Okay I see another one on https://edition.cnn.com/ 👍 

image


image

**Review by sayedtaqui — APPROVED** [review]
Looks good!

**Pull request merged**
