### PR TITLE
CLI: Check for latest version and show message

### LINKED ISSUE #815: PSAT CLI: Version Check and Update Prompt for PSAT CLI
## Feature Request

**Description:**

Implement a version check mechanism in the PSAT CLI that prompts users to update if they are running an outdated version. Additionally, include the CLI version information in all generated reports.

**Motivation:**

Users running outdated CLI versions may encounter issues or bugs that have been fixed in newer releases. This leads to unnecessary support requests and a frustrating user experience. Prompting users to update and providing version information in reports will help mitigate this problem.

**User Story:**

As a PSAT CLI user, I want to be notified if I'm running an outdated version so that I can avoid encountering known issues and get the most accurate results.

**Acceptance Criteria:**

- [ ]  When the PSAT CLI is executed, it checks for the latest version.
- [ ]  If a newer version is available, the CLI displays a message to the user, prompting them to update. The message should include clear instructions on how to update (e.g., the `npm i -g @google-psat/cli` command).
- [ ]  The PSAT CLI version used for analysis is included in the metadata of all generated reports (HTML, JSON).

**Additional Information:**

- The version check could be performed using NPM's API or by comparing the local version with a version string fetched from a remote source (e.g., `package.json` file in the GitHub repository for the CLI package).
- The update prompt message should be clear, concise, and easily noticeable by the user.

Example
```
You are currently using PSAT CLI version [current_version]. 
A newer version ([latest_version]) is available.

To get the latest features and bug fixes, please update:
npm i -g @google-psat/cli 
```

### PR DESCRIPTION
**Pull request by mohdsayed**
## Description

Add version check to the PSAT CLI to notify users when they are running an outdated version. Also, add the version is included in all generated reports for CLI and extension.

## Relevant Technical Choices

- Use the `update-notifier` package to check for the latest version and notify users.
- Use the package version from `package.json` instead of hardcoding it.
- Pass the version to the report and use it in the header component.
- Retrieve the current extension version and include it in the header of the extension report.
- Add `psatVersion` in downloaded report JSON file.

## Testing Instructions

- Go to `packages/cli/package.json` and reduce the version number.
- Build and run the CLI to test if it can check and notify about the update.
- The latest version check occurs after a certain time (e.g., 1 day) instead of running every time to reduce its impact on time and performance. This is currently disabled for easier QA testing. Once QA is complete, we'll enable it for further testing.
- Open the dashboard report and verify that the current CLI version appears in the report header.
- Download a report from the extension and confirm that the current extension version is displayed (which may differ from the CLI version).
- Download report from the CLI dashboard and check if it includes `psatVersion` key in JSON file.

## Screenshot/Screencast

image

---

## Checklist

- [x]  I have thoroughly tested this code to the best of my abilities.
- [x]  I have reviewed the code myself before requesting a review.
- [x]  This code is covered by unit tests to verify that it works as intended.
- [x]  The QA of this PR is done by a member of the QA team (to be checked by QA).

Fixes #815

### CODE REVIEW

**Comment by pavanpatil1** [comment]
Hi @mohdsayed, I’ve reviewed the PR, and it mostly works fine. However, did notice a few issues, added below: 

- [ ] The report.html file does not display the version number. It should include the CLI/Extension version number in the report.

Screenshot 2024-08-29 at 1 54 34 PM

---

- [ ] In dark mode, the extension number is difficult to see and not clearly visible.

Screenshot 2024-08-29 at 1 51 15 PM

---

- [ ] Can we update the update notification something like as follows?

```
You are currently using PSAT CLI version v0.10.0. A newer version, v0.10.1, is available.

To update to the latest version, please run the following command: npm i -g @google-psat/cli 
```

- [ ] After downgrading the CLI version (@psat/cli) in package.json, the "update available" message did not appear on the first run. It only started showing up after the second run.

**Comment by mohdsayed** [comment]
@pavanpatil1 

> The report.html file does not display the version number. It should include the CLI/Extension version number in the report.

Fixed

> In dark mode, the extension number is difficult to see and not clearly visible.

Fixed

> Can we update the update notification something like as follows?

I think that's a lot of text to read. What we are showing is very precise and already approved.

> After downgrading the CLI version (@psat/cli) in package.json, the "update available" message did not appear on the first run. It only started showing up after the second run.

I just learned that the package [update-notifier](https://www.npmjs.com/package/update-notifier) we are using works that way. Read the comment in their [example.js](https://github.com/yeoman/update-notifier/blob/main/example.js) file. I will have to seek some alternative.

**Comment by mohdsayed** [comment]
@pavanpatil1 

> After downgrading the CLI version (@psat/cli) in package.json, the "update available" message did not appear on the first run. It only started showing up after the second run.

Pushed a fix for it, can you please try again.

**Comment by pavanpatil1** [comment]
Verified the latest changes. Those are working fine.

**Review by amovar18 — APPROVED** [review]
LGTM!

**Pull request merged**
