### PR TITLE
Feature: Update `babel-loader` webpack config to have caching support for faster builds

### PR DESCRIPTION
**Pull request by gagan0123**
## Description

This PR aims to improve the build performance of our Webpack configuration by implementing caching for the Babel loader. By enabling this feature, we expect to see a significant reduction in build times, particularly during development, as Babel will be able to reuse previously computed results instead of reprocessing files from scratch on every build.

## Relevant Technical Choices

- Enabled caching in the Babel loader configuration within our Webpack setup.

## Testing Instructions

To verify the effectiveness of this change:
1. Perform a clean build of the project and note the build time.
2. Make a minor change in one of the JavaScript/TypeScript files.
3. Rebuild the project and observe the build time. There should be a noticeable reduction in build time compared to the initial build.
4. Ensure that the application still runs as expected and that there are no build-related errors.

## Additional Information:

This change is a straightforward enhancement aimed at improving developer experience by reducing waiting times during the build process when switching between branches. It does not introduce any new dependencies or major changes to our build configuration.

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- [x] This code is covered by unit tests to verify that it works as intended.
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

### CODE REVIEW

**Comment by mohdsayed** [comment]
@gagan0123 Good find, however, I wouldn't want to try this near a release. Let's try it in the `develop` branch after v0.5 to see how it works

Related comments: https://github.com/babel/babel-loader/issues/199#issuecomment-417962724, https://github.com/babel/babel-loader/issues/351#issuecomment-417968076

**Comment by gagan0123** [comment]
Created new branch, cherry-picked my commit, then force pushed to this, so as to isolate it from other changes that were being displayed, now its ready for review and merge to `develop`

**Comment by gagan0123** [comment]
cc @mohdsayed

**Comment by gagan0123** [comment]
@mohdsayed 

Anything else that needs to be added in this PR?

**Comment by mohdsayed** [comment]
> @mohdsayed
> 
> Anything else that needs to be added in this PR?

That's all for post v0.5 merge

https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/452#issuecomment-1909264041

**Comment by gagan0123** [comment]
:memo: Noted

We can assign this to QA after 0.5 release :rocket:

**Comment by fellyph** [comment]
LGTM 

I have tested all the scripts: 
- `build`
- `test`
- `cli`
- `dev`

And run the extension and test a few audits

**Review by mohdsayed — APPROVED** [review]
Merging this long pending PR.

cc: @mayan-000 , @amovar18 , @ayushnirwal

**Pull request merged**
